### ISSUE TITLE
Congrats on your paper!

### ISSUE THREAD

**Issue by thaoshibe** [sterzhang/PVIT#1]
Aaaa I just saw your paper on arXiv today!
Congrats to youu~ I just wanted to say that I agree: (1) Additional training is such a cucumber-some for current personalized models; and (2) I agree that in this task, we indeed need a dataset.

I'll read your paper later today~ Congrats again!

**Comment by sterzhang** [comment]
Thanks! Your Yo' LLaVA inspires me a lot. Welcome any discussion to further explore personalized MLLMs.
